### ISSUE TITLE
gbm dependency?

### ISSUE THREAD

**Issue by djcowper** [intel/stress-weston#11]
It may be that with Mesa-1-193 there is a new dependency on libgbm for the apps to build.
Someone should check when building on the latest Clear installer.
(fix was just to add -lgbm to the LD_LIBS line in Makefile)

**Comment by mpfife** [comment]
Just tried a clean build 28690 with software-defined-cockpit, os-clr-on-clr, and software-defined-cockpit-dev packages installed. stress-weston build ok without needing libgbm. 

We suspect this requirement may need to be added to the linker if a user builds their own version of Mesa.

Will close this as not an issue, but this will serve as documentation in case others encouter the same problem.
